@startuml

title __ESTATION's Class Diagram__\n

  namespace com.app.estation {
    class com.app.estation.EstationApplication {
    }
  }
  

  namespace com.app.estation {
    namespace advice {
      class com.app.estation.advice.AppExceptionHandler {
      }
    }
  }
  

  namespace com.app.estation {
    namespace advice {
      namespace exceptions {
        class com.app.estation.advice.exceptions.ApiRequestException {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace advice {
      namespace exceptions {
        class com.app.estation.advice.exceptions.ApiRequestOkException {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace advice {
      namespace exceptions {
        class com.app.estation.advice.exceptions.EntityNotFoundException {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace advice {
      namespace exceptions {
        class com.app.estation.advice.exceptions.TokenRefreshException {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace advice {
      namespace validation {
        interface com.app.estation.advice.validation.InsertValidation {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace advice {
      namespace validation {
        interface com.app.estation.advice.validation.UpdateValidation {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace config {
      class com.app.estation.config.ApplicationConfig {
      }
    }
  }
  

  namespace com.app.estation {
    namespace config {
      class com.app.estation.config.JwtAuthenticationFilter {
      }
    }
  }
  

  namespace com.app.estation {
    namespace config {
      class com.app.estation.config.SecurityConfiguration {
      }
    }
  }
  

  namespace com.app.estation {
    namespace controller {
      class com.app.estation.controller.CiterneController {
      }
    }
  }
  

  namespace com.app.estation {
    namespace controller {
      class com.app.estation.controller.PompeController {
      }
    }
  }
  

  namespace com.app.estation {
    namespace controller {
      class com.app.estation.controller.ProduitController {
      }
    }
  }
  

  namespace com.app.estation {
    namespace controller {
      class com.app.estation.controller.ReleveController {
      }
    }
  }
  

  namespace com.app.estation {
    namespace controller {
      class com.app.estation.controller.ServiceController {
      }
    }
  }
  

  namespace com.app.estation {
    namespace controller {
      class com.app.estation.controller.StationController {
      }
    }
  }
  

  namespace com.app.estation {
    namespace controller {
      class com.app.estation.controller.TransactionController {
      }
    }
  }
  

  namespace com.app.estation {
    namespace controller {
      class com.app.estation.controller.UserController {
      }
    }
  }
  

  namespace com.app.estation {
    namespace controller {
      namespace auth {
        class com.app.estation.controller.auth.AuthController {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.AffectationMontantDto {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.AuthDto {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.CarburantDto {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.CiterneDto {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.CiterneJaugageDto {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.CiternePompeDto {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.CiternePompeRequest {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.DebitRequest {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.EncaissementDto {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.EncaissementProduitRequest {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.EncaissementRequest {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.HistoriquePrixDto {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.LoginDto {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.PompeDto {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.PompeUserRequest {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.ProduitActionDto {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.ProduitDto {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.ProfileDto {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.RefreshTokenDto {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.RefreshTokenRequest {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.ReleveDto {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.ReleveResponse {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.ServicesDto {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.StationDto {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.StationInformationDto {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.StationUserRequest {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.TransactionDto {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.TransactionGroupDto {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.TypePaiementDto {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.TypeProduitDto {
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      namespace User {
        class com.app.estation.dto.User.PompeUserDto {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      namespace User {
        class com.app.estation.dto.User.StationUserDto {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      namespace User {
        class com.app.estation.dto.User.StationUserKeyDto {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      namespace User {
        class com.app.estation.dto.User.UserDto {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      namespace User {
        class com.app.estation.dto.User.UserPassDto {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace dto {
      class com.app.estation.dto.UserEmailRequest {
      }
    }
  }
  

  namespace com.app.estation {
    namespace entity {
      class com.app.estation.entity.Citerne {
      }
    }
  }
  

  namespace com.app.estation {
    namespace entity {
      class com.app.estation.entity.CiternePompe {
      }
    }
  }
  

  namespace com.app.estation {
    namespace entity {
      class com.app.estation.entity.HistoriquePrix {
      }
    }
  }
  

  namespace com.app.estation {
    namespace entity {
      class com.app.estation.entity.Pompe {
      }
    }
  }
  

  namespace com.app.estation {
    namespace entity {
      class com.app.estation.entity.PompeUser {
      }
    }
  }
  

  namespace com.app.estation {
    namespace entity {
      class com.app.estation.entity.Produit {
      }
    }
  }
  

  namespace com.app.estation {
    namespace entity {
      class com.app.estation.entity.ProduitAction {
      }
    }
  }
  

  namespace com.app.estation {
    namespace entity {
      class com.app.estation.entity.Profile {
      }
    }
  }
  

  namespace com.app.estation {
    namespace entity {
      class com.app.estation.entity.RefreshToken {
      }
    }
  }
  

  namespace com.app.estation {
    namespace entity {
      class com.app.estation.entity.Releve {
      }
    }
  }
  

  namespace com.app.estation {
    namespace entity {
      class com.app.estation.entity.Services {
      }
    }
  }
  

  namespace com.app.estation {
    namespace entity {
      class com.app.estation.entity.Station {
      }
    }
  }
  

  namespace com.app.estation {
    namespace entity {
      class com.app.estation.entity.StationUser {
      }
    }
  }
  

  namespace com.app.estation {
    namespace entity {
      class com.app.estation.entity.Transaction {
      }
    }
  }
  

  namespace com.app.estation {
    namespace entity {
      class com.app.estation.entity.TransactionGroup {
      }
    }
  }
  

  namespace com.app.estation {
    namespace entity {
      enum TypeAction {
      }
    }
  }
  

  namespace com.app.estation {
    namespace entity {
      class com.app.estation.entity.TypePaiement {
      }
    }
  }
  

  namespace com.app.estation {
    namespace entity {
      class com.app.estation.entity.TypeProduit {
      }
    }
  }
  

  namespace com.app.estation {
    namespace entity {
      enum TypeReleve {
      }
    }
  }
  

  namespace com.app.estation {
    namespace entity {
      enum TypeTransaction {
      }
    }
  }
  

  namespace com.app.estation {
    namespace entity {
      class com.app.estation.entity.User {
      }
    }
  }
  

  namespace com.app.estation {
    namespace mappers {
      class com.app.estation.mappers.CiterneMapper {
      }
    }
  }
  

  namespace com.app.estation {
    namespace mappers {
      class com.app.estation.mappers.CiternePompeMapper {
      }
    }
  }
  

  namespace com.app.estation {
    namespace mappers {
      class com.app.estation.mappers.HistoriquePrixMapper {
      }
    }
  }
  

  namespace com.app.estation {
    namespace mappers {
      class com.app.estation.mappers.PompeMapper {
      }
    }
  }
  

  namespace com.app.estation {
    namespace mappers {
      class com.app.estation.mappers.PompeUserMapper {
      }
    }
  }
  

  namespace com.app.estation {
    namespace mappers {
      class com.app.estation.mappers.ProduitActionMapper {
      }
    }
  }
  

  namespace com.app.estation {
    namespace mappers {
      class com.app.estation.mappers.ProduitMapper {
      }
    }
  }
  

  namespace com.app.estation {
    namespace mappers {
      class com.app.estation.mappers.ProfileMapper {
      }
    }
  }
  

  namespace com.app.estation {
    namespace mappers {
      class com.app.estation.mappers.ReleveMapper {
      }
    }
  }
  

  namespace com.app.estation {
    namespace mappers {
      class com.app.estation.mappers.ServicesMapper {
      }
    }
  }
  

  namespace com.app.estation {
    namespace mappers {
      class com.app.estation.mappers.StationMapper {
      }
    }
  }
  

  namespace com.app.estation {
    namespace mappers {
      class com.app.estation.mappers.StationUserMapper {
      }
    }
  }
  

  namespace com.app.estation {
    namespace mappers {
      class com.app.estation.mappers.TransactionGroupMapper {
      }
    }
  }
  

  namespace com.app.estation {
    namespace mappers {
      class com.app.estation.mappers.TransactionMapper {
      }
    }
  }
  

  namespace com.app.estation {
    namespace mappers {
      class com.app.estation.mappers.TypePaiementMapper {
      }
    }
  }
  

  namespace com.app.estation {
    namespace mappers {
      class com.app.estation.mappers.TypeProduitMapper {
      }
    }
  }
  

  namespace com.app.estation {
    namespace mappers {
      class com.app.estation.mappers.UserMapper {
      }
    }
  }
  

  namespace com.app.estation {
    namespace repository {
      interface com.app.estation.repository.CiternePompeRepository {
      }
    }
  }
  

  namespace com.app.estation {
    namespace repository {
      interface com.app.estation.repository.CiterneRepository {
      }
    }
  }
  

  namespace com.app.estation {
    namespace repository {
      interface com.app.estation.repository.HistoriquePrixRepository {
      }
    }
  }
  

  namespace com.app.estation {
    namespace repository {
      interface com.app.estation.repository.PompeRepository {
      }
    }
  }
  

  namespace com.app.estation {
    namespace repository {
      interface com.app.estation.repository.PompeUserRepository {
      }
    }
  }
  

  namespace com.app.estation {
    namespace repository {
      interface com.app.estation.repository.ProduitActionRepository {
      }
    }
  }
  

  namespace com.app.estation {
    namespace repository {
      interface com.app.estation.repository.ProduitRepository {
      }
    }
  }
  

  namespace com.app.estation {
    namespace repository {
      interface com.app.estation.repository.ProfileRepository {
      }
    }
  }
  

  namespace com.app.estation {
    namespace repository {
      interface com.app.estation.repository.RefreshTokenRepository {
      }
    }
  }
  

  namespace com.app.estation {
    namespace repository {
      interface com.app.estation.repository.ReleveRepository {
      }
    }
  }
  

  namespace com.app.estation {
    namespace repository {
      interface com.app.estation.repository.ServiceRepository {
      }
    }
  }
  

  namespace com.app.estation {
    namespace repository {
      interface com.app.estation.repository.StationRepository {
      }
    }
  }
  

  namespace com.app.estation {
    namespace repository {
      interface com.app.estation.repository.StationUserRepository {
      }
    }
  }
  

  namespace com.app.estation {
    namespace repository {
      interface com.app.estation.repository.TransactionGroupRepository {
      }
    }
  }
  

  namespace com.app.estation {
    namespace repository {
      interface com.app.estation.repository.TransactionRepository {
      }
    }
  }
  

  namespace com.app.estation {
    namespace repository {
      interface com.app.estation.repository.TypePaiementRepository {
      }
    }
  }
  

  namespace com.app.estation {
    namespace repository {
      interface com.app.estation.repository.TypeProduitRepository {
      }
    }
  }
  

  namespace com.app.estation {
    namespace repository {
      interface com.app.estation.repository.UserRepository {
      }
    }
  }
  

  namespace com.app.estation {
    namespace service {
      interface com.app.estation.service.EServices {
      }
    }
  }
  

  namespace com.app.estation {
    namespace service {
      interface com.app.estation.service.RefreshTokenService {
      }
    }
  }
  

  namespace com.app.estation {
    namespace service {
      namespace implementation {
        class com.app.estation.service.implementation.AuthService {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace service {
      namespace implementation {
        class com.app.estation.service.implementation.CiternePompeServiceImpl {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace service {
      namespace implementation {
        class com.app.estation.service.implementation.CiterneServiceImpl {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace service {
      namespace implementation {
        class com.app.estation.service.implementation.HistoriquePrixServiceImpl {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace service {
      namespace implementation {
        class com.app.estation.service.implementation.JwtService {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace service {
      namespace implementation {
        class com.app.estation.service.implementation.PompeServiceImpl {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace service {
      namespace implementation {
        class com.app.estation.service.implementation.PompeUserServiceImpl {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace service {
      namespace implementation {
        class com.app.estation.service.implementation.ProduitServiceImpl {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace service {
      namespace implementation {
        class com.app.estation.service.implementation.RefreshTokenServiceImpl {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace service {
      namespace implementation {
        class com.app.estation.service.implementation.ReleveServiceImpl {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace service {
      namespace implementation {
        class com.app.estation.service.implementation.ServicesImpl {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace service {
      namespace implementation {
        class com.app.estation.service.implementation.StationServiceImpl {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace service {
      namespace implementation {
        class com.app.estation.service.implementation.StationUserServiceImpl {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace service {
      namespace implementation {
        class com.app.estation.service.implementation.TransactionServiceImpl {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace service {
      namespace implementation {
        class com.app.estation.service.implementation.TypeProduitServiceImpl {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace service {
      namespace implementation {
        class com.app.estation.service.implementation.UserServiceImpl {
        }
      }
    }
  }
  

  namespace com.app.estation {
    namespace util {
      class com.app.estation.util.DateFormatter {
      }
    }
  }
  

  namespace com.app.estation {
    namespace util {
      class com.app.estation.util.FullnessCalculator {
      }
    }
  }
  

  namespace com.app.estation {
    namespace util {
      class com.app.estation.util.PassEncode {
      }
    }
  }
  

  namespace com.app.estation {
    namespace util {
      class com.app.estation.util.PriceCalculator {
      }
    }
  }
  

  com.app.estation.config.ApplicationConfig o-- com.app.estation.repository.UserRepository : userRepository
  com.app.estation.config.JwtAuthenticationFilter -up-|> org.springframework.web.filter.OncePerRequestFilter
  com.app.estation.config.JwtAuthenticationFilter o-- com.app.estation.service.implementation.JwtService : jwtService
  com.app.estation.config.SecurityConfiguration o-- com.app.estation.config.JwtAuthenticationFilter : jwtAuthFilter
  com.app.estation.controller.CiterneController o-- com.app.estation.service.implementation.CiterneServiceImpl : citerneService
  com.app.estation.controller.PompeController o-- com.app.estation.service.implementation.CiternePompeServiceImpl : citernePompeService
  com.app.estation.controller.PompeController o-- com.app.estation.service.implementation.PompeServiceImpl : pompeService
  com.app.estation.controller.ProduitController o-- com.app.estation.service.implementation.ProduitServiceImpl : produitService
  com.app.estation.controller.ProduitController o-- com.app.estation.service.implementation.TypeProduitServiceImpl : typeProduitService
  com.app.estation.controller.ReleveController o-- com.app.estation.service.implementation.ReleveServiceImpl : releveService
  com.app.estation.controller.ServiceController o-- com.app.estation.service.implementation.ServicesImpl : servicesService
  com.app.estation.controller.StationController o-- com.app.estation.service.implementation.ServicesImpl : servicesService
  com.app.estation.controller.StationController o-- com.app.estation.service.implementation.StationServiceImpl : stationService
  com.app.estation.controller.TransactionController o-- com.app.estation.service.implementation.TransactionServiceImpl : transactionService
  com.app.estation.controller.UserController o-- com.app.estation.service.implementation.PompeUserServiceImpl : pompeUserService
  com.app.estation.controller.UserController o-- com.app.estation.service.implementation.StationUserServiceImpl : stationUserService
  com.app.estation.controller.UserController o-- com.app.estation.service.implementation.UserServiceImpl : userService
  com.app.estation.controller.auth.AuthController o-- com.app.estation.service.implementation.AuthService : authService
  com.app.estation.controller.auth.AuthController o-- com.app.estation.util.PassEncode : passEncode
  com.app.estation.dto.AffectationMontantDto o-- com.app.estation.dto.User.PompeUserDto : pompeUser
  com.app.estation.dto.AuthDto o-- com.app.estation.dto.User.UserDto : user
  com.app.estation.dto.CiterneDto o-- com.app.estation.dto.ProduitDto : produit
  com.app.estation.dto.CiterneDto o-- com.app.estation.dto.StationDto : station
  com.app.estation.dto.CiternePompeDto o-- com.app.estation.dto.CiterneDto : citerne
  com.app.estation.dto.CiternePompeDto o-- com.app.estation.dto.PompeDto : pompe
  com.app.estation.dto.EncaissementDto o-- com.app.estation.dto.TypePaiementDto : typePaiement
  com.app.estation.dto.HistoriquePrixDto o-- com.app.estation.dto.ProduitDto : idProduit
  com.app.estation.dto.ProduitActionDto o-- com.app.estation.entity.TypeAction : action
  com.app.estation.dto.ProduitActionDto o-- com.app.estation.dto.ProduitDto : produit
  com.app.estation.dto.ProduitDto o-- com.app.estation.dto.ServicesDto : service
  com.app.estation.dto.ProduitDto o-- com.app.estation.dto.TypeProduitDto : type
  com.app.estation.dto.ReleveDto o-- com.app.estation.dto.User.PompeUserDto : pompeUser
  com.app.estation.dto.ServicesDto o-- com.app.estation.dto.StationDto : station
  com.app.estation.dto.TransactionDto o-- com.app.estation.dto.TransactionGroupDto : idTransactionGroup
  com.app.estation.dto.TransactionDto o-- com.app.estation.entity.TypePaiement : typePaiement
  com.app.estation.dto.TransactionGroupDto o-- com.app.estation.dto.User.PompeUserDto : idPompeUser
  com.app.estation.dto.TransactionGroupDto o-- com.app.estation.dto.ProduitActionDto : idProduitAction
  com.app.estation.dto.TransactionGroupDto o-- com.app.estation.dto.StationDto : station
  com.app.estation.dto.TransactionGroupDto o-- com.app.estation.entity.TypeTransaction : typeTransaction
  com.app.estation.dto.User.PompeUserDto o-- com.app.estation.dto.PompeDto : pompe
  com.app.estation.dto.User.PompeUserDto o-- com.app.estation.dto.User.UserDto : user
  com.app.estation.dto.User.StationUserDto o-- com.app.estation.dto.StationDto : station
  com.app.estation.dto.User.StationUserDto o-- com.app.estation.dto.User.UserDto : user
  com.app.estation.dto.User.UserDto o-- com.app.estation.dto.ProfileDto : profile
  com.app.estation.entity.Citerne o-- com.app.estation.entity.Produit : id_produit
  com.app.estation.entity.Citerne o-- com.app.estation.entity.Station : station
  com.app.estation.entity.CiternePompe o-- com.app.estation.entity.Citerne : citerne
  com.app.estation.entity.CiternePompe o-- com.app.estation.entity.Pompe : pompe
  com.app.estation.entity.HistoriquePrix o-- com.app.estation.entity.Produit : idProduit
  com.app.estation.entity.PompeUser o-- com.app.estation.entity.Pompe : pompe
  com.app.estation.entity.PompeUser o-- com.app.estation.entity.User : user
  com.app.estation.entity.Produit o-- com.app.estation.entity.Services : id_service
  com.app.estation.entity.Produit o-- com.app.estation.entity.TypeProduit : type
  com.app.estation.entity.ProduitAction o-- com.app.estation.entity.TypeAction : action
  com.app.estation.entity.ProduitAction o-- com.app.estation.entity.Produit : produit
  com.app.estation.entity.Profile .up.|> java.io.Serializable
  com.app.estation.entity.RefreshToken o-- com.app.estation.entity.User : user
  com.app.estation.entity.Releve o-- com.app.estation.entity.PompeUser : pompeUser
  com.app.estation.entity.Releve o-- com.app.estation.entity.TypeReleve : type_releve
  com.app.estation.entity.Services o-- com.app.estation.entity.Station : station
  com.app.estation.entity.StationUser o-- com.app.estation.entity.Station : station
  com.app.estation.entity.StationUser o-- com.app.estation.entity.User : user
  com.app.estation.entity.Transaction o-- com.app.estation.entity.TransactionGroup : idTransactionGroup
  com.app.estation.entity.Transaction o-- com.app.estation.entity.TypePaiement : typePaiement
  com.app.estation.entity.TransactionGroup o-- com.app.estation.entity.PompeUser : idPompeUser
  com.app.estation.entity.TransactionGroup o-- com.app.estation.entity.ProduitAction : idProduitAction
  com.app.estation.entity.TransactionGroup o-- com.app.estation.entity.Station : station
  com.app.estation.entity.TransactionGroup o-- com.app.estation.entity.TypeTransaction : typeTransaction
  com.app.estation.entity.User .up.|> org.springframework.security.core.userdetails.UserDetails
  com.app.estation.entity.User o-- com.app.estation.entity.Profile : profile
  com.app.estation.entity.User o-- com.app.estation.entity.RefreshToken : refreshToken
  com.app.estation.service.implementation.AuthService o-- com.app.estation.service.implementation.JwtService : jwtService
  com.app.estation.service.implementation.AuthService o-- com.app.estation.util.PassEncode : passEncode
  com.app.estation.service.implementation.AuthService o-- com.app.estation.service.RefreshTokenService : refreshTokenService
  com.app.estation.service.implementation.AuthService o-- com.app.estation.repository.UserRepository : userRepository
  com.app.estation.service.implementation.CiternePompeServiceImpl .up.|> com.app.estation.service.EServices
  com.app.estation.service.implementation.CiternePompeServiceImpl o-- com.app.estation.repository.CiternePompeRepository : citernePompeRepository
  com.app.estation.service.implementation.CiternePompeServiceImpl o-- com.app.estation.repository.CiterneRepository : citerneRepository
  com.app.estation.service.implementation.CiternePompeServiceImpl o-- com.app.estation.repository.PompeRepository : pompeRepository
  com.app.estation.service.implementation.CiterneServiceImpl .up.|> com.app.estation.service.EServices
  com.app.estation.service.implementation.CiterneServiceImpl o-- com.app.estation.repository.CiterneRepository : citerneRepository
  com.app.estation.service.implementation.CiterneServiceImpl o-- com.app.estation.repository.ProduitRepository : produitRepository
  com.app.estation.service.implementation.CiterneServiceImpl o-- com.app.estation.repository.StationRepository : stationRepository
  com.app.estation.service.implementation.HistoriquePrixServiceImpl .up.|> com.app.estation.service.EServices
  com.app.estation.service.implementation.HistoriquePrixServiceImpl o-- com.app.estation.repository.HistoriquePrixRepository : historiquePrixRepository
  com.app.estation.service.implementation.PompeServiceImpl .up.|> com.app.estation.service.EServices
  com.app.estation.service.implementation.PompeServiceImpl o-- com.app.estation.repository.CiternePompeRepository : citernePompeRepository
  com.app.estation.service.implementation.PompeServiceImpl o-- com.app.estation.repository.PompeRepository : pompeRepository
  com.app.estation.service.implementation.PompeUserServiceImpl .up.|> com.app.estation.service.EServices
  com.app.estation.service.implementation.PompeUserServiceImpl o-- com.app.estation.repository.CiternePompeRepository : citernePompeRepository
  com.app.estation.service.implementation.PompeUserServiceImpl o-- com.app.estation.repository.PompeRepository : pompeRepository
  com.app.estation.service.implementation.PompeUserServiceImpl o-- com.app.estation.repository.PompeUserRepository : pompeUserRepository
  com.app.estation.service.implementation.PompeUserServiceImpl o-- com.app.estation.service.implementation.ReleveServiceImpl : releveService
  com.app.estation.service.implementation.PompeUserServiceImpl o-- com.app.estation.repository.TransactionGroupRepository : transactionGroupRepository
  com.app.estation.service.implementation.PompeUserServiceImpl o-- com.app.estation.repository.UserRepository : userRepository
  com.app.estation.service.implementation.ProduitServiceImpl .up.|> com.app.estation.service.EServices
  com.app.estation.service.implementation.ProduitServiceImpl o-- com.app.estation.repository.HistoriquePrixRepository : historiquePrixRepository
  com.app.estation.service.implementation.ProduitServiceImpl o-- com.app.estation.service.implementation.HistoriquePrixServiceImpl : historiquePrixServiceImpl
  com.app.estation.service.implementation.ProduitServiceImpl o-- com.app.estation.repository.ProduitRepository : produitRepository
  com.app.estation.service.implementation.ProduitServiceImpl o-- com.app.estation.repository.ServiceRepository : serviceRepository
  com.app.estation.service.implementation.ProduitServiceImpl o-- com.app.estation.repository.TypeProduitRepository : typeProduitRepository
  com.app.estation.service.implementation.RefreshTokenServiceImpl .up.|> com.app.estation.service.RefreshTokenService
  com.app.estation.service.implementation.RefreshTokenServiceImpl o-- com.app.estation.repository.RefreshTokenRepository : refreshTokenRepository
  com.app.estation.service.implementation.RefreshTokenServiceImpl o-- com.app.estation.repository.UserRepository : userRepository
  com.app.estation.service.implementation.ReleveServiceImpl .up.|> com.app.estation.service.EServices
  com.app.estation.service.implementation.ReleveServiceImpl o-- com.app.estation.repository.CiternePompeRepository : citernePompeRepository
  com.app.estation.service.implementation.ReleveServiceImpl o-- com.app.estation.repository.PompeUserRepository : pompeUserRepository
  com.app.estation.service.implementation.ReleveServiceImpl o-- com.app.estation.repository.ReleveRepository : releveRepository
  com.app.estation.service.implementation.ReleveServiceImpl o-- com.app.estation.repository.UserRepository : userRepository
  com.app.estation.service.implementation.ServicesImpl .up.|> com.app.estation.service.EServices
  com.app.estation.service.implementation.ServicesImpl o-- com.app.estation.repository.ServiceRepository : serviceRepository
  com.app.estation.service.implementation.ServicesImpl o-- com.app.estation.repository.StationRepository : stationRepository
  com.app.estation.service.implementation.StationServiceImpl .up.|> com.app.estation.service.EServices
  com.app.estation.service.implementation.StationServiceImpl o-- com.app.estation.repository.CiterneRepository : citerneRepository
  com.app.estation.service.implementation.StationServiceImpl o-- com.app.estation.repository.HistoriquePrixRepository : historiquePrixRepository
  com.app.estation.service.implementation.StationServiceImpl o-- com.app.estation.repository.ProduitRepository : produitRepository
  com.app.estation.service.implementation.StationServiceImpl o-- com.app.estation.repository.ServiceRepository : serviceRepository
  com.app.estation.service.implementation.StationServiceImpl o-- com.app.estation.repository.StationRepository : stationRepository
  com.app.estation.service.implementation.StationServiceImpl o-- com.app.estation.repository.TransactionGroupRepository : transactionGroupRepository
  com.app.estation.service.implementation.StationUserServiceImpl .up.|> com.app.estation.service.EServices
  com.app.estation.service.implementation.StationUserServiceImpl o-- com.app.estation.repository.StationRepository : stationRepository
  com.app.estation.service.implementation.StationUserServiceImpl o-- com.app.estation.repository.UserRepository : userRepository
  com.app.estation.service.implementation.StationUserServiceImpl o-- com.app.estation.service.implementation.StationServiceImpl : stationService
  com.app.estation.service.implementation.StationUserServiceImpl o-- com.app.estation.repository.StationUserRepository : stationUserRepository
  com.app.estation.service.implementation.StationUserServiceImpl o-- com.app.estation.service.implementation.UserServiceImpl : userService
  com.app.estation.service.implementation.TransactionServiceImpl .up.|> com.app.estation.service.EServices
  com.app.estation.service.implementation.TransactionServiceImpl o-- com.app.estation.service.implementation.CiterneServiceImpl : citerneService
  com.app.estation.service.implementation.TransactionServiceImpl o-- com.app.estation.repository.PompeUserRepository : pompeUserRepository
  com.app.estation.service.implementation.TransactionServiceImpl o-- com.app.estation.service.implementation.PompeUserServiceImpl : pompeUserService
  com.app.estation.service.implementation.TransactionServiceImpl o-- com.app.estation.repository.ProduitActionRepository : produitActionRepository
  com.app.estation.service.implementation.TransactionServiceImpl o-- com.app.estation.repository.ProduitRepository : produitRepository
  com.app.estation.service.implementation.TransactionServiceImpl o-- com.app.estation.service.implementation.ReleveServiceImpl : releveService
  com.app.estation.service.implementation.TransactionServiceImpl o-- com.app.estation.service.implementation.StationServiceImpl : stationService
  com.app.estation.service.implementation.TransactionServiceImpl o-- com.app.estation.repository.TransactionGroupRepository : transactionGroupRepository
  com.app.estation.service.implementation.TransactionServiceImpl o-- com.app.estation.repository.TransactionRepository : transactionRepository
  com.app.estation.service.implementation.TransactionServiceImpl o-- com.app.estation.repository.TypePaiementRepository : typePaiementRepository
  com.app.estation.service.implementation.TypeProduitServiceImpl .up.|> com.app.estation.service.EServices
  com.app.estation.service.implementation.TypeProduitServiceImpl o-- com.app.estation.repository.TypeProduitRepository : typeProduitRepository
  com.app.estation.service.implementation.UserServiceImpl .up.|> com.app.estation.service.EServices
  com.app.estation.service.implementation.UserServiceImpl o-- com.app.estation.util.PassEncode : passEncode
  com.app.estation.service.implementation.UserServiceImpl o-- com.app.estation.service.implementation.JwtService : jwtService
  com.app.estation.service.implementation.UserServiceImpl o-- com.app.estation.repository.ProfileRepository : profileRepository
  com.app.estation.service.implementation.UserServiceImpl o-- com.app.estation.repository.UserRepository : userRepository
  com.app.estation.util.PassEncode -up-|> org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
